
default_platform(:android)

platform :android do

 desc "testing"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :sentToTester do
        firebase_app_distribution(
            app: "1:514414649029:android:c8b7bf212192b571129aac",
            groups: "hi",
            release_notes: "final version",
            firebase_cli_path: "1//0ghZUR1zLkNFyCgYIARAAGBASNwF-L9IrzO5yz3ipMH5eimCQGMNHsLtHdw-yZxGorB98nThLg8SA5ah8I2uoTCtmj3nQYAfuSoQ",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end
