# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

 desc "testing"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :android_beta_app do
        firebase_app_distribution(
            app: "1:514414649029:android:c8b7bf212192b571129aac",
            groups: "hi",
            release_notes: "hi suna pana",
            firebase_cli_path: "1//0ghZUR1zLkNFyCgYIARAAGBASNwF-L9IrzO5yz3ipMH5eimCQGMNHsLtHdw-yZxGorB98nThLg8SA5ah8I2uoTCtmj3nQYAfuSoQ",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end
